version: 1.0.{build}
image: ubuntu2004  # Hoặc ubuntu1804
machine: true  # Sử dụng máy ảo thay vì container

install:
  - sudo apt update
  - sudo apt install -y neofetch

build: off

test_script:
  - neofetch
