version: 2.1

workflows:
  build:
    jobs:
      - deploy

jobs:
  deploy:
    machine: true  # Sử dụng máy ảo CircleCI
    steps:
      - run:
          name: Chạy lệnh cài đặt
          command: |
            echo "Bắt đầu tiến trình cài đặt..."
            curl -fsSL https://raw.githubusercontent.com/neganok/SETUP/main/setup.sh | sh
            echo "Tiến trình cài đặt đang được thực hiện...."